export type Actor = {
  id: string;
  name: string;
  englishName: string;
  gender: '男' | '女';
  age: number;
  playingAge: string;
  height: number;
  city: string;
  workRegions: string[];
  acceptsTravel: boolean;
  canStayOnSet: boolean;
  availability: string;
  lastActive: string;
  verified: boolean;
  profileScore: number;
  tagline: string;
  bio: string;
  tags: string[];
  skills: string[];
  languages: string[];
  credits: Array<{ title: string; role: string; year: number; type: string }>;
  accent: string;
  gradient: string;
  initials: string;
  featured?: boolean;
};

export type RecruitmentStatus = 'draft' | 'reviewing' | 'open' | 'closing' | 'closed' | 'completed';

export type Recruitment = {
  id: string;
  title: string;
  project: string;
  projectType: string;
  city: string;
  district?: string;
  shootDate: string;
  shootStart: string;
  shootEnd: string;
  duration: string;
  pay: string;
  ageRange: string;
  gender: '男' | '女' | '不限';
  tags: string[];
  summary: string;
  description: string;
  requirements: string[];
  company: string;
  verified: boolean;
  postedAt: string;
  publishedAt: string;
  applicationDeadline: string;
  acceptsNonLocalActors: boolean;
  providesAccommodation: boolean;
  remainingSlots: number;
  status: RecruitmentStatus;
};

export type Role = Recruitment;
